version: "3.8"

services:
  php:
    build:
      context: .
      target: php_dev
      args:
        UID: 1000
        GID: 1000
    volumes:
      - .:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  nginx:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
